/**
 * @deprecated Prefer `leadCategories` from Redux (seeded via SQL).
 * Kept as a fallback reference list matching the bootstrap seed.
 */
export const DEFAULT_ONBOARDING_BUSINESS_TYPES: readonly string[] = [
  'Accountants',
  'Auto Repair',
  'Bakeries',
  'Barbers',
  'Cafes',
  'Car Dealerships',
  'Chiropractors',
  'Cleaning Services',
  'Dentists',
  'Electricians',
  'Florists',
  'Gyms',
  'Hair Salons',
  'HVAC',
  'Insurance Agents',
  'Interior Designers',
  'Landscapers',
  'Lawyers',
  'Martial Arts Schools',
  'Moving Companies',
  'Nail Salons',
  'Optometrists',
  'Pest Control',
  'Pet Groomers',
  'Photographers',
  'Physical Therapists',
  'Plumbers',
  'Real Estate Agents',
  'Restaurants',
  'Roofers',
  'Spas',
  'Storage Facilities',
  'Tattoo Shops',
  'Tax Preparers',
  'Tire Shops',
  'Towing Services',
  'Veterinarians',
  'Wedding Venues',
  'Yoga Studios',
] as const;
